#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="Hack Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)
POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11
POPUP_BACKGROUND_COLOR=$BLACK
POPUP_BORDER_COLOR=$COMMENT
CORNER_RADIUS=15
BORDER_WIDTH=2
SHADOW=off

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

#Setting up the general bar appearance of the bar
bar=(
  height=35
  color=$BAR_COLOR
  border_width=0
  border_color=$BAR_BORDER_COLOR
  shadow="$SHADOW"
  position=top
  sticky=on
  padding_right=5
  padding_left=5
  corner_radius="$CORNER_RADIUS"
  y_offset=3
  margin=5
  blur_radius=20
	notch_width=200
  topmost=window
)

sketchybar --bar "${bar[@]}"

#Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:13.5"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Bold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_left=$PADDINGS
  padding_right=$PADDINGS
  background.padding_left="$PADDINGS"
  background.padding_right="$PADDINGS"
  background.height=26
  background.corner_radius=15
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=11
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing="$SHADOW"
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# ===========================================================

# Register custom event - this will be use by sketchybar's space items as well as app_space.sh
sketchybar --add event window_change

# ===========================================================

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

#source "$ITEM_DIR/dynamic_spaces.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/media.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"
#source "$ITEM_DIR/focus.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/mic.sh"
source "$ITEM_DIR/volume.sh"
#source "$ITEM_DIR/svim.sh"

status_bracket=(
  background.color=$BACKGROUND_1
  background.border_color=$BACKGROUND_2
)

# Brackets (Grouped Items)
sketchybar --add bracket all_spaces '/space\..*/'                   \
           --set  all_spaces  background.color=$BACKGROUND_1        \
                              background.corner_radius=9.75         \
                              background.border_color=$YELLOW       \
                              background.border_width=2             \

sketchybar --add bracket status brew github.bell wifi volume_icon   \
           --set status       background.color=$BACKGROUND_1        \
                              background.border_color=$BACKGROUND_2 \                            

# Auto-restart sketchybar on safe file.
sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
